/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorTelefono;
import ec.edu.ups.modelo.Telefono;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Paul Idrovo
 */
public class ListaTelefonoVista extends javax.swing.JFrame {

    private TelefonoVista vistaTelefono;
    private ControladorTelefono controladorTelefono;

    public ListaTelefonoVista(TelefonoVista vsTelefono, ControladorTelefono ctrlTelefono) {
        initComponents();
        controladorTelefono = ctrlTelefono;
        vistaTelefono = vsTelefono;
        this.setLocationRelativeTo(this);
        this.setResizable(false);
    }

    public void listar() {
        List<Telefono> listaTelefonos = controladorTelefono.verTelefonos();

        DefaultListModel modelo = new DefaultListModel();
        for (Telefono telefono : listaTelefonos) {
            modelo.addElement(telefono.toString());
        }
        lstTelefonos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstTelefonos = new javax.swing.JList<>();
        btRegresar = new javax.swing.JButton();
        btRegresar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("LISTA DE TELEFONOS");

        lstTelefonos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LISTA DE TELEFONOS", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 1, 14))); // NOI18N
        lstTelefonos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lstTelefonos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstTelefonos.setMaximumSize(new java.awt.Dimension(278, 250));
        lstTelefonos.setMinimumSize(new java.awt.Dimension(278, 250));
        jScrollPane1.setViewportView(lstTelefonos);

        btRegresar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btRegresar.setText("REGRESAR");
        btRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegresarActionPerformed(evt);
            }
        });

        btRegresar1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btRegresar1.setText("LISTAR");
        btRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegresar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(btRegresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRegresar)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRegresar)
                    .addComponent(btRegresar1))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegresarActionPerformed
        // TODO add your handling code here:
        vistaTelefono.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btRegresarActionPerformed

    private void btRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegresar1ActionPerformed
        listar();
    }//GEN-LAST:event_btRegresar1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegresar;
    private javax.swing.JButton btRegresar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstTelefonos;
    // End of variables declaration//GEN-END:variables
}
